# anomaly_detection_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection
  labels:
    app: anomaly-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detection
  template:
    metadata:
      labels:
        app: anomaly-detection
    spec:
      containers:
      - name: anomaly-detection
        image: 869472115623.dkr.ecr.ap-southeast-1.amazonaws.com/anomaly-detection:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection-service
spec:
  selector:
    app: anomaly-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
