# data_ingestion_
deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  labels:
    app: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: 869472115623.dkr.ecr.ap-southeast-1.amazonaws.com/data-ingestion:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
spec:
  selector:
    app: data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
