# preprocessing-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
  labels:
    app: preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
      - name: preprocessing
        image: 869472115623.dkr.ecr.ap-southeast-1.amazonaws.com/preprocessing:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
spec:
  selector:
    app: preprocessing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
